name: CI

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: 'false'

      - name: Build
        run: make build-all

      - name: Unit Tests
        run: make unit-test
