name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Setup smimecosign
      run: |
        set -e
        go install .
        mkdir /tmp/git
        cd /tmp/git
        git init .
        git config --global user.email "test@example.com"
        git config --global user.name "smimecosign"
        git config --global gpg.x509.program smimecosign
        git config --global gpg.format x509
        git commit --allow-empty --message="Signed commit"
        git --no-pager log --show-signature -1

